@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

interface Media
class Main
class Movies
class Series
class UserMenu
class Dashboard
class MovieHandler
class UserHandler
interface UI
interface IO
abstract RollingPictures

package "util"{
class TextUI
class UserIO
}

Media : String getTitle()
Media : int getYear()
Media : int getCategory()
Media : int getRating()

Main : + static void main(string [] args)

Movies : ArrayList<Movies>
Movies : + Movies(String title, String year, String category, String rating, String fileName)
Movies : + loadMovies()
Movies : + saveMovie()
Movies : + toString()

Series : + Series(String title, String year, String category, String rating)

UserMenu : + setupUserMenu()

Dashboard : + setupDashboard()

MovieHandler : - List<Movies>
MovieHandler : + searchMovieByName(String movieName)
MovieHandler : + searchMovieBycategory(String movieName)
MovieHandler : + readMoviesFromCSV(String fileName)
MovieHandler : + searchmovie()
MovieHandler : + searchmoviecategory()
MovieHandler : + showAllMovies()
MovieHandler : + createMovie(String[] metadata)
MovieHandler : + movieList(String filePath)

UserHandler : + UserHandler(String filename)
UserHandler : + login(String username, String password, String id)
UserHandler : + createUser(String username, String password, String id)
UserHandler : + loadUsers()
UserHandler : + saveUsers()
UserHandler : + isUserNameValid(String username)
UserHandler : + isValid(String password)

RollingPictures : - title
RollingPictures : - year
RollingPictures : - category
RollingPictures : - rating
RollingPictures : + RollingPictures(String title, String year,String category, String rating)
RollingPictures : + RollingPictures(String fileName)
RollingPictures : + getTitle()
RollingPictures : + getYear()
RollingPictures : + getCategory()
RollingPictures : + getRating()
RollingPictures : + toString()

Main *-- UserMenu
UserMenu *-- Dashboard
Dashboard *--Media
Dashboard *-- UserHandler
Dashboard *-- MovieHandler
Media *-- RollingPictures

RollingPictures <|-- Movies
RollingPictures <|-- Series
Movies *-- UserPick
Series *-- UserPick

UI <|-- TextUI
IO <|-- UserIO



@enduml