@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

interface Medie
class Main
class Movies
class Series
class UserMenu
class Dashboard
class UserPick
class MedieHandler
class UserHandler
interface UI
interface IO
abstract RollingPictures

package "util"{
class TextUI
class UserIO
}

Media : String getTitle()
Media : int getYear()
Media : int getCategory()
Media : int getRating()

Movies : - String title
Movies : - int year
Movies : - String category
Movies : - int rating

Series : - String title
Series : - int year
Series : - String category
Series : - int rating
Series : - int seasonEpisodes

RollingPictures : - title
RollingPictures : - year
RollingPictures : - category
RollingPictures : - rating
RollingPictures : + getTitle()
RollingPictures : + getYear()
RollingPictures : + getCategory()
RollingPictures : + getRating()
RollingPictures : + toString()

UserPick : + void addMedie()
UserPick : + void removeMedie()
UserPick : + void playMedie()
UserHandler : void håndterer login og bruger data
MedieHandler : void håndterer film og serier i Lister

Main *-- UserMenu
UserMenu *-- Dashboard
Dashboard *--Media
Dashboard *-- UserHandler
Dashboard *-- MedieHandler
Media *-- RollingPictures

RollingPictures <|-- Movies
RollingPictures <|-- Series
Movies *-- UserPick
Series *-- UserPick

UI <|-- TextUI
IO <|-- UserIO



@enduml