@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

interface Media
class Main
class Movies
class Series
class UserMenu
class Dashboard
class UserPick
class MediaHandler
class UserHandler
interface UI
interface IO
abstract RollingPictures



package "util"{
class TextUI
class UserIO
}

Media : String getTitle()
Media : int getYear()
Media : int getCategory()
Media : int Rating()

Movies : - String title
Movies : - int Year
Movies : - String category 1,2,3
Movies : - int Rating

Series : - String title
Series : - int Year
Series : - String category 1,2,3
Series : - int Rating
Series : - int season/Episode

UserPick : + void addMedia()
UserPick : + void removeMedia()
UserPick : + void playMedia()
UserHandler : void håndterer login og bruger data
MediaHandler : void håndterer film og serier i Lister

Main *-- UserMenu
UserMenu *-- Dashboard
Dashboard *--Media
Dashboard *-- UserHandler
Dashboard *-- MediaHandler
Media *-- RollingPictures

RollingPictures <|-- Movies
RollingPictures <|-- Series
Movies *-- UserPick
Series *-- UserPick

UI <|-- TextUI
IO <|-- UserIO



@enduml